/* eslint-disable */
import * as types from './graphql';
import type { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';

/**
 * Map of all GraphQL operations in the project.
 *
 * This map has several performance disadvantages:
 * 1. It is not tree-shakeable, so it will include all operations in the project.
 * 2. It is not minifiable, so the string of a GraphQL query will be multiple times inside the bundle.
 * 3. It does not support dead code elimination, so it will add unused operations.
 *
 * Therefore it is highly recommended to use the babel or swc plugin for production.
 * Learn more about it here: https://the-guild.dev/graphql/codegen/plugins/presets/preset-client#reducing-bundle-size
 */
type Documents = {
    "\n  mutation ApproveAccessRequest($requestId: String!) {\n    approveAccessRequest(requestId: $requestId) {\n      id\n      status\n      resolvedAt\n    }\n  }\n": typeof types.ApproveAccessRequestDocument,
    "\n  mutation RejectAccessRequest($input: RejectAccessRequestInput!) {\n    rejectAccessRequest(input: $input) {\n      id\n      status\n      rejectionReason\n      resolvedAt\n    }\n  }\n": typeof types.RejectAccessRequestDocument,
    "\n  mutation LoginResident($input: LoginResidentInput!) {\n    loginResident(input: $input) {\n      accessToken\n      refreshToken\n      expiresIn\n      sessionId\n    }\n  }\n": typeof types.LoginResidentDocument,
    "\n  mutation RefreshToken($refreshToken: String!) {\n    refreshToken(refreshToken: $refreshToken) {\n      accessToken\n      refreshToken\n      expiresIn\n      sessionId\n    }\n  }\n": typeof types.RefreshTokenDocument,
    "\n  query GetMyResidentProfile {\n    myResidentProfile {\n      id\n      type\n      status\n      isMainResident\n      startDate\n      user {\n        id\n        name\n        lastName\n        email\n        phoneNumber\n        identity\n        rating\n      }\n      unit {\n        id\n        number\n        floor\n        building {\n          id\n          name\n          floors\n        }\n      }\n      complex {\n        id\n        name\n      }\n    }\n  }\n": typeof types.GetMyResidentProfileDocument,
    "\n  query GetUnitBalance($unitId: String!, $complexId: String!) {\n    unitBalance(unitId: $unitId, complexId: $complexId) {\n      unitId\n      unitNumber\n      totalDebt\n      overdueCount\n      pendingCount\n      totalPaid\n    }\n  }\n": typeof types.GetUnitBalanceDocument,
    "\n  query GetUnitAccountStatement($unitId: String!, $complexId: String!, $period: String) {\n    unitAccountStatement(unitId: $unitId, complexId: $complexId, period: $period) {\n      unitId\n      unitNumber\n      building\n      totalDebits\n      totalCredits\n      currentBalance\n      walletBalance\n      movements {\n        id\n        date\n        type\n        description\n        debit\n        credit\n        balance\n        reference\n      }\n    }\n  }\n": typeof types.GetUnitAccountStatementDocument,
    "\n  query GetPaymentsByCharge($chargeId: String!) {\n    paymentsByCharge(chargeId: $chargeId) {\n      id\n      amount\n      method\n      reference\n      receiptUrl\n      paidAt\n      notes\n      isReversed\n      reversalReason\n      reversedAt\n      createdAt\n    }\n  }\n": typeof types.GetPaymentsByChargeDocument,
    "\n  query GetUnitWallet($unitId: String!, $complexId: String!) {\n    unitWallet(unitId: $unitId, complexId: $complexId) {\n      unitId\n      unitNumber\n      building\n      currentBalance\n      totalCredits\n      totalDebits\n      entries {\n        id\n        type\n        amount\n        description\n        chargeId\n        createdAt\n      }\n    }\n  }\n": typeof types.GetUnitWalletDocument,
    "\n  mutation SaveMobileToken($input: SaveMobileTokenInput!) {\n    saveMobileToken(input: $input) {\n      success\n    }\n  }\n": typeof types.SaveMobileTokenDocument,
    "\n  mutation MarkNotificationAsRead($notificationId: String!) {\n    markNotificationAsRead(notificationId: $notificationId) {\n      id\n      isRead\n      readAt\n    }\n  }\n": typeof types.MarkNotificationAsReadDocument,
    "\n  mutation MarkAllNotificationsAsRead($complexId: String!) {\n    markAllNotificationsAsRead(complexId: $complexId)\n  }\n": typeof types.MarkAllNotificationsAsReadDocument,
    "\n  mutation DeleteNotification($notificationId: String!) {\n    deleteNotification(notificationId: $notificationId)\n  }\n": typeof types.DeleteNotificationDocument,
    "\n  query MyNotifications(\n    $complexId: String!\n    $pagination: PaginationInput\n    $filters: FilterNotificationsInput\n  ) {\n    myNotifications(complexId: $complexId, pagination: $pagination, filters: $filters) {\n      items {\n        id\n        type\n        priority\n        title\n        body\n        isRead\n        isActionable\n        entityType\n        entityId\n        metadata\n        createdAt\n      }\n      pagination {\n        currentPage\n        itemsPerPage\n        totalItems\n        totalPages\n        hasNextPage\n        hasPreviousPage\n      }\n    }\n  }\n": typeof types.MyNotificationsDocument,
    "\n  query UnreadNotificationsCount($complexId: String!) {\n    unreadNotificationsCount(complexId: $complexId) {\n      count\n    }\n  }\n": typeof types.UnreadNotificationsCountDocument,
    "\n  query NotificationDetail($notificationId: String!, $complexId: String!) {\n    notificationDetail(notificationId: $notificationId, complexId: $complexId) {\n      id\n      type\n      priority\n      title\n      body\n      isRead\n      isActionable\n      actionType\n      actionLabel\n      actionResult\n      entityType\n      entityId\n      metadata\n      createdByUser {\n        id\n        fullName\n        roles\n        profilePicture\n      }\n    }\n  }\n": typeof types.NotificationDetailDocument,
    "\n  query MyUnitPackages($complexId: String!, $pagination: PaginationInput, $filters: FilterPackagesInput) {\n    myUnitPackages(complexId: $complexId, pagination: $pagination, filters: $filters) {\n      items {\n        id\n        trackingCode\n        senderName\n        description\n        type\n        status\n        photoUrl\n        receivedAt\n        notifiedAt\n        deliveredAt\n        returnedAt\n        recipientName\n        receivedByName\n        notes\n        returnReason\n        unitId\n        complexId\n      }\n      pagination {\n        currentPage\n        itemsPerPage\n        totalItems\n        totalPages\n        hasNextPage\n        hasPreviousPage\n      }\n    }\n  }\n": typeof types.MyUnitPackagesDocument,
    "\n  query Package($packageId: String!) {\n    package(packageId: $packageId) {\n      id\n      trackingCode\n      senderName\n      description\n      type\n      status\n      photoUrl\n      receivedAt\n      notifiedAt\n      deliveredAt\n      returnedAt\n      recipientName\n      receivedByName\n      notes\n      returnReason\n      unitId\n      complexId\n    }\n  }\n": typeof types.PackageDocument,
    "\n  mutation TriggerPanicAlert($complexId: String!) {\n    triggerPanicAlert(complexId: $complexId) {\n      success\n    }\n  }\n": typeof types.TriggerPanicAlertDocument,
    "\n  mutation AcknowledgePanicAlert($notificationId: String!) {\n    acknowledgePanicAlert(notificationId: $notificationId) {\n      id\n      complexId\n    }\n  }\n": typeof types.AcknowledgePanicAlertDocument,
    "\n  query GetUnit($id: String!) {\n    unit(id: $id) {\n      id\n      number\n      floor\n      building {\n        id\n        name\n      }\n    }\n  }\n": typeof types.GetUnitDocument,
    "\n  query ActivePanicAlerts($complexId: String!) {\n    activePanicAlerts(complexId: $complexId) {\n      id\n      complexId\n      createdByUserId\n      metadata\n      createdAt\n    }\n  }\n": typeof types.ActivePanicAlertsDocument,
    "\n  mutation RequestSecurityCall($complexId: String!) {\n    requestSecurityCall(complexId: $complexId) {\n      success\n      message\n    }\n  }\n": typeof types.RequestSecurityCallDocument,
    "\n  query Vehicle($id: String!) {\n    vehicle(id: $id) {\n      id\n      plate\n      type\n      brand\n      model\n      year\n      color\n      fuelType\n      photoUrl\n      parkingSpot\n      status\n      approvedAt\n      rejectionReason\n      notes\n      residentId\n      unitId\n      complexId\n      createdAt\n    }\n  }\n": typeof types.VehicleDocument,
    "\n  mutation ScheduleVisit($input: ScheduleVisitInput!) {\n    scheduleVisit(input: $input) {\n      id\n      status\n      type\n      qrToken\n      qrExpiresAt\n      expectedArrivalAt\n      expectedArrivalUntil\n      createdAt\n      visitor {\n        id\n        fullName\n        identity\n        identityType\n        phone\n      }\n    }\n  }\n": typeof types.ScheduleVisitDocument,
    "\n  mutation ApproveVisit($visitId: String!) {\n    approveVisitEntry(visitId: $visitId) {\n      id\n      status\n      approvedByResidentAt\n    }\n  }\n": typeof types.ApproveVisitDocument,
    "\n  mutation DenyVisit($visitId: String!, $reason: String!) {\n    denyVisitEntry(visitId: $visitId, reason: $reason) {\n      id\n      status\n      denialReason\n      deniedByResidentAt\n    }\n  }\n": typeof types.DenyVisitDocument,
    "\n  mutation CancelVisit($visitId: String!) {\n    cancelVisit(visitId: $visitId) {\n      id\n      status\n    }\n  }\n": typeof types.CancelVisitDocument,
    "\n  mutation BlacklistVisitor($input: BlacklistVisitorInput!) {\n    blacklistVisitor(input: $input) {\n      id\n      name\n      lastName\n      identity\n      isBlacklisted\n      blacklistReason\n      blacklistedAt\n    }\n  }\n": typeof types.BlacklistVisitorDocument,
    "\n  mutation RemoveVisitorFromBlacklist($visitorId: String!) {\n    removeVisitorFromBlacklist(visitorId: $visitorId) {\n      id\n      name\n      lastName\n      identity\n      isBlacklisted\n      blacklistReason\n      blacklistedAt\n    }\n  }\n": typeof types.RemoveVisitorFromBlacklistDocument,
    "\n  query Visit($id: String!) {\n    visit(id: $id) {\n      id\n      type\n      status\n      purpose\n      entryTime\n      exitTime\n      expectedArrivalAt\n      expectedArrivalUntil\n      vehiclePlate\n      denialReason\n      notes\n      approvedByResidentAt\n      deniedByResidentAt\n      createdAt\n      visitor {\n        id\n        name\n        lastName\n        identity\n        identityType\n        phone\n        photoUrl\n        isBlacklisted\n      }\n    }\n  }\n": typeof types.VisitDocument,
    "\n  query MisVisitas($pagination: PaginationInput, $filters: FilterVisitsInput) {\n    myVisits(pagination: $pagination, filters: $filters) {\n      items {\n        id\n        type\n        status\n        purpose\n        expectedArrivalAt\n        expectedArrivalUntil\n        qrToken\n        qrUsed\n        qrExpiresAt\n        vehiclePlate\n        entryTime\n        exitTime\n        createdAt\n        visitor {\n          id\n          name\n          lastName\n          identity\n          identityType\n          phone\n          photoUrl\n          isBlacklisted\n          blacklistReason\n          blacklistedAt\n        }\n        unit {\n          id\n          building {\n            id\n            name\n          }\n        }\n      }\n      pagination {\n        currentPage\n        itemsPerPage\n        totalItems\n        totalPages\n        hasNextPage\n        hasPreviousPage\n      }\n    }\n  }\n": typeof types.MisVisitasDocument,
};
const documents: Documents = {
    "\n  mutation ApproveAccessRequest($requestId: String!) {\n    approveAccessRequest(requestId: $requestId) {\n      id\n      status\n      resolvedAt\n    }\n  }\n": types.ApproveAccessRequestDocument,
    "\n  mutation RejectAccessRequest($input: RejectAccessRequestInput!) {\n    rejectAccessRequest(input: $input) {\n      id\n      status\n      rejectionReason\n      resolvedAt\n    }\n  }\n": types.RejectAccessRequestDocument,
    "\n  mutation LoginResident($input: LoginResidentInput!) {\n    loginResident(input: $input) {\n      accessToken\n      refreshToken\n      expiresIn\n      sessionId\n    }\n  }\n": types.LoginResidentDocument,
    "\n  mutation RefreshToken($refreshToken: String!) {\n    refreshToken(refreshToken: $refreshToken) {\n      accessToken\n      refreshToken\n      expiresIn\n      sessionId\n    }\n  }\n": types.RefreshTokenDocument,
    "\n  query GetMyResidentProfile {\n    myResidentProfile {\n      id\n      type\n      status\n      isMainResident\n      startDate\n      user {\n        id\n        name\n        lastName\n        email\n        phoneNumber\n        identity\n        rating\n      }\n      unit {\n        id\n        number\n        floor\n        building {\n          id\n          name\n          floors\n        }\n      }\n      complex {\n        id\n        name\n      }\n    }\n  }\n": types.GetMyResidentProfileDocument,
    "\n  query GetUnitBalance($unitId: String!, $complexId: String!) {\n    unitBalance(unitId: $unitId, complexId: $complexId) {\n      unitId\n      unitNumber\n      totalDebt\n      overdueCount\n      pendingCount\n      totalPaid\n    }\n  }\n": types.GetUnitBalanceDocument,
    "\n  query GetUnitAccountStatement($unitId: String!, $complexId: String!, $period: String) {\n    unitAccountStatement(unitId: $unitId, complexId: $complexId, period: $period) {\n      unitId\n      unitNumber\n      building\n      totalDebits\n      totalCredits\n      currentBalance\n      walletBalance\n      movements {\n        id\n        date\n        type\n        description\n        debit\n        credit\n        balance\n        reference\n      }\n    }\n  }\n": types.GetUnitAccountStatementDocument,
    "\n  query GetPaymentsByCharge($chargeId: String!) {\n    paymentsByCharge(chargeId: $chargeId) {\n      id\n      amount\n      method\n      reference\n      receiptUrl\n      paidAt\n      notes\n      isReversed\n      reversalReason\n      reversedAt\n      createdAt\n    }\n  }\n": types.GetPaymentsByChargeDocument,
    "\n  query GetUnitWallet($unitId: String!, $complexId: String!) {\n    unitWallet(unitId: $unitId, complexId: $complexId) {\n      unitId\n      unitNumber\n      building\n      currentBalance\n      totalCredits\n      totalDebits\n      entries {\n        id\n        type\n        amount\n        description\n        chargeId\n        createdAt\n      }\n    }\n  }\n": types.GetUnitWalletDocument,
    "\n  mutation SaveMobileToken($input: SaveMobileTokenInput!) {\n    saveMobileToken(input: $input) {\n      success\n    }\n  }\n": types.SaveMobileTokenDocument,
    "\n  mutation MarkNotificationAsRead($notificationId: String!) {\n    markNotificationAsRead(notificationId: $notificationId) {\n      id\n      isRead\n      readAt\n    }\n  }\n": types.MarkNotificationAsReadDocument,
    "\n  mutation MarkAllNotificationsAsRead($complexId: String!) {\n    markAllNotificationsAsRead(complexId: $complexId)\n  }\n": types.MarkAllNotificationsAsReadDocument,
    "\n  mutation DeleteNotification($notificationId: String!) {\n    deleteNotification(notificationId: $notificationId)\n  }\n": types.DeleteNotificationDocument,
    "\n  query MyNotifications(\n    $complexId: String!\n    $pagination: PaginationInput\n    $filters: FilterNotificationsInput\n  ) {\n    myNotifications(complexId: $complexId, pagination: $pagination, filters: $filters) {\n      items {\n        id\n        type\n        priority\n        title\n        body\n        isRead\n        isActionable\n        entityType\n        entityId\n        metadata\n        createdAt\n      }\n      pagination {\n        currentPage\n        itemsPerPage\n        totalItems\n        totalPages\n        hasNextPage\n        hasPreviousPage\n      }\n    }\n  }\n": types.MyNotificationsDocument,
    "\n  query UnreadNotificationsCount($complexId: String!) {\n    unreadNotificationsCount(complexId: $complexId) {\n      count\n    }\n  }\n": types.UnreadNotificationsCountDocument,
    "\n  query NotificationDetail($notificationId: String!, $complexId: String!) {\n    notificationDetail(notificationId: $notificationId, complexId: $complexId) {\n      id\n      type\n      priority\n      title\n      body\n      isRead\n      isActionable\n      actionType\n      actionLabel\n      actionResult\n      entityType\n      entityId\n      metadata\n      createdByUser {\n        id\n        fullName\n        roles\n        profilePicture\n      }\n    }\n  }\n": types.NotificationDetailDocument,
    "\n  query MyUnitPackages($complexId: String!, $pagination: PaginationInput, $filters: FilterPackagesInput) {\n    myUnitPackages(complexId: $complexId, pagination: $pagination, filters: $filters) {\n      items {\n        id\n        trackingCode\n        senderName\n        description\n        type\n        status\n        photoUrl\n        receivedAt\n        notifiedAt\n        deliveredAt\n        returnedAt\n        recipientName\n        receivedByName\n        notes\n        returnReason\n        unitId\n        complexId\n      }\n      pagination {\n        currentPage\n        itemsPerPage\n        totalItems\n        totalPages\n        hasNextPage\n        hasPreviousPage\n      }\n    }\n  }\n": types.MyUnitPackagesDocument,
    "\n  query Package($packageId: String!) {\n    package(packageId: $packageId) {\n      id\n      trackingCode\n      senderName\n      description\n      type\n      status\n      photoUrl\n      receivedAt\n      notifiedAt\n      deliveredAt\n      returnedAt\n      recipientName\n      receivedByName\n      notes\n      returnReason\n      unitId\n      complexId\n    }\n  }\n": types.PackageDocument,
    "\n  mutation TriggerPanicAlert($complexId: String!) {\n    triggerPanicAlert(complexId: $complexId) {\n      success\n    }\n  }\n": types.TriggerPanicAlertDocument,
    "\n  mutation AcknowledgePanicAlert($notificationId: String!) {\n    acknowledgePanicAlert(notificationId: $notificationId) {\n      id\n      complexId\n    }\n  }\n": types.AcknowledgePanicAlertDocument,
    "\n  query GetUnit($id: String!) {\n    unit(id: $id) {\n      id\n      number\n      floor\n      building {\n        id\n        name\n      }\n    }\n  }\n": types.GetUnitDocument,
    "\n  query ActivePanicAlerts($complexId: String!) {\n    activePanicAlerts(complexId: $complexId) {\n      id\n      complexId\n      createdByUserId\n      metadata\n      createdAt\n    }\n  }\n": types.ActivePanicAlertsDocument,
    "\n  mutation RequestSecurityCall($complexId: String!) {\n    requestSecurityCall(complexId: $complexId) {\n      success\n      message\n    }\n  }\n": types.RequestSecurityCallDocument,
    "\n  query Vehicle($id: String!) {\n    vehicle(id: $id) {\n      id\n      plate\n      type\n      brand\n      model\n      year\n      color\n      fuelType\n      photoUrl\n      parkingSpot\n      status\n      approvedAt\n      rejectionReason\n      notes\n      residentId\n      unitId\n      complexId\n      createdAt\n    }\n  }\n": types.VehicleDocument,
    "\n  mutation ScheduleVisit($input: ScheduleVisitInput!) {\n    scheduleVisit(input: $input) {\n      id\n      status\n      type\n      qrToken\n      qrExpiresAt\n      expectedArrivalAt\n      expectedArrivalUntil\n      createdAt\n      visitor {\n        id\n        fullName\n        identity\n        identityType\n        phone\n      }\n    }\n  }\n": types.ScheduleVisitDocument,
    "\n  mutation ApproveVisit($visitId: String!) {\n    approveVisitEntry(visitId: $visitId) {\n      id\n      status\n      approvedByResidentAt\n    }\n  }\n": types.ApproveVisitDocument,
    "\n  mutation DenyVisit($visitId: String!, $reason: String!) {\n    denyVisitEntry(visitId: $visitId, reason: $reason) {\n      id\n      status\n      denialReason\n      deniedByResidentAt\n    }\n  }\n": types.DenyVisitDocument,
    "\n  mutation CancelVisit($visitId: String!) {\n    cancelVisit(visitId: $visitId) {\n      id\n      status\n    }\n  }\n": types.CancelVisitDocument,
    "\n  mutation BlacklistVisitor($input: BlacklistVisitorInput!) {\n    blacklistVisitor(input: $input) {\n      id\n      name\n      lastName\n      identity\n      isBlacklisted\n      blacklistReason\n      blacklistedAt\n    }\n  }\n": types.BlacklistVisitorDocument,
    "\n  mutation RemoveVisitorFromBlacklist($visitorId: String!) {\n    removeVisitorFromBlacklist(visitorId: $visitorId) {\n      id\n      name\n      lastName\n      identity\n      isBlacklisted\n      blacklistReason\n      blacklistedAt\n    }\n  }\n": types.RemoveVisitorFromBlacklistDocument,
    "\n  query Visit($id: String!) {\n    visit(id: $id) {\n      id\n      type\n      status\n      purpose\n      entryTime\n      exitTime\n      expectedArrivalAt\n      expectedArrivalUntil\n      vehiclePlate\n      denialReason\n      notes\n      approvedByResidentAt\n      deniedByResidentAt\n      createdAt\n      visitor {\n        id\n        name\n        lastName\n        identity\n        identityType\n        phone\n        photoUrl\n        isBlacklisted\n      }\n    }\n  }\n": types.VisitDocument,
    "\n  query MisVisitas($pagination: PaginationInput, $filters: FilterVisitsInput) {\n    myVisits(pagination: $pagination, filters: $filters) {\n      items {\n        id\n        type\n        status\n        purpose\n        expectedArrivalAt\n        expectedArrivalUntil\n        qrToken\n        qrUsed\n        qrExpiresAt\n        vehiclePlate\n        entryTime\n        exitTime\n        createdAt\n        visitor {\n          id\n          name\n          lastName\n          identity\n          identityType\n          phone\n          photoUrl\n          isBlacklisted\n          blacklistReason\n          blacklistedAt\n        }\n        unit {\n          id\n          building {\n            id\n            name\n          }\n        }\n      }\n      pagination {\n        currentPage\n        itemsPerPage\n        totalItems\n        totalPages\n        hasNextPage\n        hasPreviousPage\n      }\n    }\n  }\n": types.MisVisitasDocument,
};

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 *
 *
 * @example
 * ```ts
 * const query = graphql(`query GetUser($id: ID!) { user(id: $id) { name } }`);
 * ```
 *
 * The query argument is unknown!
 * Please regenerate the types.
 */
export function graphql(source: string): unknown;

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation ApproveAccessRequest($requestId: String!) {\n    approveAccessRequest(requestId: $requestId) {\n      id\n      status\n      resolvedAt\n    }\n  }\n"): (typeof documents)["\n  mutation ApproveAccessRequest($requestId: String!) {\n    approveAccessRequest(requestId: $requestId) {\n      id\n      status\n      resolvedAt\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation RejectAccessRequest($input: RejectAccessRequestInput!) {\n    rejectAccessRequest(input: $input) {\n      id\n      status\n      rejectionReason\n      resolvedAt\n    }\n  }\n"): (typeof documents)["\n  mutation RejectAccessRequest($input: RejectAccessRequestInput!) {\n    rejectAccessRequest(input: $input) {\n      id\n      status\n      rejectionReason\n      resolvedAt\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation LoginResident($input: LoginResidentInput!) {\n    loginResident(input: $input) {\n      accessToken\n      refreshToken\n      expiresIn\n      sessionId\n    }\n  }\n"): (typeof documents)["\n  mutation LoginResident($input: LoginResidentInput!) {\n    loginResident(input: $input) {\n      accessToken\n      refreshToken\n      expiresIn\n      sessionId\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation RefreshToken($refreshToken: String!) {\n    refreshToken(refreshToken: $refreshToken) {\n      accessToken\n      refreshToken\n      expiresIn\n      sessionId\n    }\n  }\n"): (typeof documents)["\n  mutation RefreshToken($refreshToken: String!) {\n    refreshToken(refreshToken: $refreshToken) {\n      accessToken\n      refreshToken\n      expiresIn\n      sessionId\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GetMyResidentProfile {\n    myResidentProfile {\n      id\n      type\n      status\n      isMainResident\n      startDate\n      user {\n        id\n        name\n        lastName\n        email\n        phoneNumber\n        identity\n        rating\n      }\n      unit {\n        id\n        number\n        floor\n        building {\n          id\n          name\n          floors\n        }\n      }\n      complex {\n        id\n        name\n      }\n    }\n  }\n"): (typeof documents)["\n  query GetMyResidentProfile {\n    myResidentProfile {\n      id\n      type\n      status\n      isMainResident\n      startDate\n      user {\n        id\n        name\n        lastName\n        email\n        phoneNumber\n        identity\n        rating\n      }\n      unit {\n        id\n        number\n        floor\n        building {\n          id\n          name\n          floors\n        }\n      }\n      complex {\n        id\n        name\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GetUnitBalance($unitId: String!, $complexId: String!) {\n    unitBalance(unitId: $unitId, complexId: $complexId) {\n      unitId\n      unitNumber\n      totalDebt\n      overdueCount\n      pendingCount\n      totalPaid\n    }\n  }\n"): (typeof documents)["\n  query GetUnitBalance($unitId: String!, $complexId: String!) {\n    unitBalance(unitId: $unitId, complexId: $complexId) {\n      unitId\n      unitNumber\n      totalDebt\n      overdueCount\n      pendingCount\n      totalPaid\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GetUnitAccountStatement($unitId: String!, $complexId: String!, $period: String) {\n    unitAccountStatement(unitId: $unitId, complexId: $complexId, period: $period) {\n      unitId\n      unitNumber\n      building\n      totalDebits\n      totalCredits\n      currentBalance\n      walletBalance\n      movements {\n        id\n        date\n        type\n        description\n        debit\n        credit\n        balance\n        reference\n      }\n    }\n  }\n"): (typeof documents)["\n  query GetUnitAccountStatement($unitId: String!, $complexId: String!, $period: String) {\n    unitAccountStatement(unitId: $unitId, complexId: $complexId, period: $period) {\n      unitId\n      unitNumber\n      building\n      totalDebits\n      totalCredits\n      currentBalance\n      walletBalance\n      movements {\n        id\n        date\n        type\n        description\n        debit\n        credit\n        balance\n        reference\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GetPaymentsByCharge($chargeId: String!) {\n    paymentsByCharge(chargeId: $chargeId) {\n      id\n      amount\n      method\n      reference\n      receiptUrl\n      paidAt\n      notes\n      isReversed\n      reversalReason\n      reversedAt\n      createdAt\n    }\n  }\n"): (typeof documents)["\n  query GetPaymentsByCharge($chargeId: String!) {\n    paymentsByCharge(chargeId: $chargeId) {\n      id\n      amount\n      method\n      reference\n      receiptUrl\n      paidAt\n      notes\n      isReversed\n      reversalReason\n      reversedAt\n      createdAt\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GetUnitWallet($unitId: String!, $complexId: String!) {\n    unitWallet(unitId: $unitId, complexId: $complexId) {\n      unitId\n      unitNumber\n      building\n      currentBalance\n      totalCredits\n      totalDebits\n      entries {\n        id\n        type\n        amount\n        description\n        chargeId\n        createdAt\n      }\n    }\n  }\n"): (typeof documents)["\n  query GetUnitWallet($unitId: String!, $complexId: String!) {\n    unitWallet(unitId: $unitId, complexId: $complexId) {\n      unitId\n      unitNumber\n      building\n      currentBalance\n      totalCredits\n      totalDebits\n      entries {\n        id\n        type\n        amount\n        description\n        chargeId\n        createdAt\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation SaveMobileToken($input: SaveMobileTokenInput!) {\n    saveMobileToken(input: $input) {\n      success\n    }\n  }\n"): (typeof documents)["\n  mutation SaveMobileToken($input: SaveMobileTokenInput!) {\n    saveMobileToken(input: $input) {\n      success\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation MarkNotificationAsRead($notificationId: String!) {\n    markNotificationAsRead(notificationId: $notificationId) {\n      id\n      isRead\n      readAt\n    }\n  }\n"): (typeof documents)["\n  mutation MarkNotificationAsRead($notificationId: String!) {\n    markNotificationAsRead(notificationId: $notificationId) {\n      id\n      isRead\n      readAt\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation MarkAllNotificationsAsRead($complexId: String!) {\n    markAllNotificationsAsRead(complexId: $complexId)\n  }\n"): (typeof documents)["\n  mutation MarkAllNotificationsAsRead($complexId: String!) {\n    markAllNotificationsAsRead(complexId: $complexId)\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation DeleteNotification($notificationId: String!) {\n    deleteNotification(notificationId: $notificationId)\n  }\n"): (typeof documents)["\n  mutation DeleteNotification($notificationId: String!) {\n    deleteNotification(notificationId: $notificationId)\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query MyNotifications(\n    $complexId: String!\n    $pagination: PaginationInput\n    $filters: FilterNotificationsInput\n  ) {\n    myNotifications(complexId: $complexId, pagination: $pagination, filters: $filters) {\n      items {\n        id\n        type\n        priority\n        title\n        body\n        isRead\n        isActionable\n        entityType\n        entityId\n        metadata\n        createdAt\n      }\n      pagination {\n        currentPage\n        itemsPerPage\n        totalItems\n        totalPages\n        hasNextPage\n        hasPreviousPage\n      }\n    }\n  }\n"): (typeof documents)["\n  query MyNotifications(\n    $complexId: String!\n    $pagination: PaginationInput\n    $filters: FilterNotificationsInput\n  ) {\n    myNotifications(complexId: $complexId, pagination: $pagination, filters: $filters) {\n      items {\n        id\n        type\n        priority\n        title\n        body\n        isRead\n        isActionable\n        entityType\n        entityId\n        metadata\n        createdAt\n      }\n      pagination {\n        currentPage\n        itemsPerPage\n        totalItems\n        totalPages\n        hasNextPage\n        hasPreviousPage\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query UnreadNotificationsCount($complexId: String!) {\n    unreadNotificationsCount(complexId: $complexId) {\n      count\n    }\n  }\n"): (typeof documents)["\n  query UnreadNotificationsCount($complexId: String!) {\n    unreadNotificationsCount(complexId: $complexId) {\n      count\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query NotificationDetail($notificationId: String!, $complexId: String!) {\n    notificationDetail(notificationId: $notificationId, complexId: $complexId) {\n      id\n      type\n      priority\n      title\n      body\n      isRead\n      isActionable\n      actionType\n      actionLabel\n      actionResult\n      entityType\n      entityId\n      metadata\n      createdByUser {\n        id\n        fullName\n        roles\n        profilePicture\n      }\n    }\n  }\n"): (typeof documents)["\n  query NotificationDetail($notificationId: String!, $complexId: String!) {\n    notificationDetail(notificationId: $notificationId, complexId: $complexId) {\n      id\n      type\n      priority\n      title\n      body\n      isRead\n      isActionable\n      actionType\n      actionLabel\n      actionResult\n      entityType\n      entityId\n      metadata\n      createdByUser {\n        id\n        fullName\n        roles\n        profilePicture\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query MyUnitPackages($complexId: String!, $pagination: PaginationInput, $filters: FilterPackagesInput) {\n    myUnitPackages(complexId: $complexId, pagination: $pagination, filters: $filters) {\n      items {\n        id\n        trackingCode\n        senderName\n        description\n        type\n        status\n        photoUrl\n        receivedAt\n        notifiedAt\n        deliveredAt\n        returnedAt\n        recipientName\n        receivedByName\n        notes\n        returnReason\n        unitId\n        complexId\n      }\n      pagination {\n        currentPage\n        itemsPerPage\n        totalItems\n        totalPages\n        hasNextPage\n        hasPreviousPage\n      }\n    }\n  }\n"): (typeof documents)["\n  query MyUnitPackages($complexId: String!, $pagination: PaginationInput, $filters: FilterPackagesInput) {\n    myUnitPackages(complexId: $complexId, pagination: $pagination, filters: $filters) {\n      items {\n        id\n        trackingCode\n        senderName\n        description\n        type\n        status\n        photoUrl\n        receivedAt\n        notifiedAt\n        deliveredAt\n        returnedAt\n        recipientName\n        receivedByName\n        notes\n        returnReason\n        unitId\n        complexId\n      }\n      pagination {\n        currentPage\n        itemsPerPage\n        totalItems\n        totalPages\n        hasNextPage\n        hasPreviousPage\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query Package($packageId: String!) {\n    package(packageId: $packageId) {\n      id\n      trackingCode\n      senderName\n      description\n      type\n      status\n      photoUrl\n      receivedAt\n      notifiedAt\n      deliveredAt\n      returnedAt\n      recipientName\n      receivedByName\n      notes\n      returnReason\n      unitId\n      complexId\n    }\n  }\n"): (typeof documents)["\n  query Package($packageId: String!) {\n    package(packageId: $packageId) {\n      id\n      trackingCode\n      senderName\n      description\n      type\n      status\n      photoUrl\n      receivedAt\n      notifiedAt\n      deliveredAt\n      returnedAt\n      recipientName\n      receivedByName\n      notes\n      returnReason\n      unitId\n      complexId\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation TriggerPanicAlert($complexId: String!) {\n    triggerPanicAlert(complexId: $complexId) {\n      success\n    }\n  }\n"): (typeof documents)["\n  mutation TriggerPanicAlert($complexId: String!) {\n    triggerPanicAlert(complexId: $complexId) {\n      success\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation AcknowledgePanicAlert($notificationId: String!) {\n    acknowledgePanicAlert(notificationId: $notificationId) {\n      id\n      complexId\n    }\n  }\n"): (typeof documents)["\n  mutation AcknowledgePanicAlert($notificationId: String!) {\n    acknowledgePanicAlert(notificationId: $notificationId) {\n      id\n      complexId\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GetUnit($id: String!) {\n    unit(id: $id) {\n      id\n      number\n      floor\n      building {\n        id\n        name\n      }\n    }\n  }\n"): (typeof documents)["\n  query GetUnit($id: String!) {\n    unit(id: $id) {\n      id\n      number\n      floor\n      building {\n        id\n        name\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query ActivePanicAlerts($complexId: String!) {\n    activePanicAlerts(complexId: $complexId) {\n      id\n      complexId\n      createdByUserId\n      metadata\n      createdAt\n    }\n  }\n"): (typeof documents)["\n  query ActivePanicAlerts($complexId: String!) {\n    activePanicAlerts(complexId: $complexId) {\n      id\n      complexId\n      createdByUserId\n      metadata\n      createdAt\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation RequestSecurityCall($complexId: String!) {\n    requestSecurityCall(complexId: $complexId) {\n      success\n      message\n    }\n  }\n"): (typeof documents)["\n  mutation RequestSecurityCall($complexId: String!) {\n    requestSecurityCall(complexId: $complexId) {\n      success\n      message\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query Vehicle($id: String!) {\n    vehicle(id: $id) {\n      id\n      plate\n      type\n      brand\n      model\n      year\n      color\n      fuelType\n      photoUrl\n      parkingSpot\n      status\n      approvedAt\n      rejectionReason\n      notes\n      residentId\n      unitId\n      complexId\n      createdAt\n    }\n  }\n"): (typeof documents)["\n  query Vehicle($id: String!) {\n    vehicle(id: $id) {\n      id\n      plate\n      type\n      brand\n      model\n      year\n      color\n      fuelType\n      photoUrl\n      parkingSpot\n      status\n      approvedAt\n      rejectionReason\n      notes\n      residentId\n      unitId\n      complexId\n      createdAt\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation ScheduleVisit($input: ScheduleVisitInput!) {\n    scheduleVisit(input: $input) {\n      id\n      status\n      type\n      qrToken\n      qrExpiresAt\n      expectedArrivalAt\n      expectedArrivalUntil\n      createdAt\n      visitor {\n        id\n        fullName\n        identity\n        identityType\n        phone\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation ScheduleVisit($input: ScheduleVisitInput!) {\n    scheduleVisit(input: $input) {\n      id\n      status\n      type\n      qrToken\n      qrExpiresAt\n      expectedArrivalAt\n      expectedArrivalUntil\n      createdAt\n      visitor {\n        id\n        fullName\n        identity\n        identityType\n        phone\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation ApproveVisit($visitId: String!) {\n    approveVisitEntry(visitId: $visitId) {\n      id\n      status\n      approvedByResidentAt\n    }\n  }\n"): (typeof documents)["\n  mutation ApproveVisit($visitId: String!) {\n    approveVisitEntry(visitId: $visitId) {\n      id\n      status\n      approvedByResidentAt\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation DenyVisit($visitId: String!, $reason: String!) {\n    denyVisitEntry(visitId: $visitId, reason: $reason) {\n      id\n      status\n      denialReason\n      deniedByResidentAt\n    }\n  }\n"): (typeof documents)["\n  mutation DenyVisit($visitId: String!, $reason: String!) {\n    denyVisitEntry(visitId: $visitId, reason: $reason) {\n      id\n      status\n      denialReason\n      deniedByResidentAt\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation CancelVisit($visitId: String!) {\n    cancelVisit(visitId: $visitId) {\n      id\n      status\n    }\n  }\n"): (typeof documents)["\n  mutation CancelVisit($visitId: String!) {\n    cancelVisit(visitId: $visitId) {\n      id\n      status\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation BlacklistVisitor($input: BlacklistVisitorInput!) {\n    blacklistVisitor(input: $input) {\n      id\n      name\n      lastName\n      identity\n      isBlacklisted\n      blacklistReason\n      blacklistedAt\n    }\n  }\n"): (typeof documents)["\n  mutation BlacklistVisitor($input: BlacklistVisitorInput!) {\n    blacklistVisitor(input: $input) {\n      id\n      name\n      lastName\n      identity\n      isBlacklisted\n      blacklistReason\n      blacklistedAt\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation RemoveVisitorFromBlacklist($visitorId: String!) {\n    removeVisitorFromBlacklist(visitorId: $visitorId) {\n      id\n      name\n      lastName\n      identity\n      isBlacklisted\n      blacklistReason\n      blacklistedAt\n    }\n  }\n"): (typeof documents)["\n  mutation RemoveVisitorFromBlacklist($visitorId: String!) {\n    removeVisitorFromBlacklist(visitorId: $visitorId) {\n      id\n      name\n      lastName\n      identity\n      isBlacklisted\n      blacklistReason\n      blacklistedAt\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query Visit($id: String!) {\n    visit(id: $id) {\n      id\n      type\n      status\n      purpose\n      entryTime\n      exitTime\n      expectedArrivalAt\n      expectedArrivalUntil\n      vehiclePlate\n      denialReason\n      notes\n      approvedByResidentAt\n      deniedByResidentAt\n      createdAt\n      visitor {\n        id\n        name\n        lastName\n        identity\n        identityType\n        phone\n        photoUrl\n        isBlacklisted\n      }\n    }\n  }\n"): (typeof documents)["\n  query Visit($id: String!) {\n    visit(id: $id) {\n      id\n      type\n      status\n      purpose\n      entryTime\n      exitTime\n      expectedArrivalAt\n      expectedArrivalUntil\n      vehiclePlate\n      denialReason\n      notes\n      approvedByResidentAt\n      deniedByResidentAt\n      createdAt\n      visitor {\n        id\n        name\n        lastName\n        identity\n        identityType\n        phone\n        photoUrl\n        isBlacklisted\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query MisVisitas($pagination: PaginationInput, $filters: FilterVisitsInput) {\n    myVisits(pagination: $pagination, filters: $filters) {\n      items {\n        id\n        type\n        status\n        purpose\n        expectedArrivalAt\n        expectedArrivalUntil\n        qrToken\n        qrUsed\n        qrExpiresAt\n        vehiclePlate\n        entryTime\n        exitTime\n        createdAt\n        visitor {\n          id\n          name\n          lastName\n          identity\n          identityType\n          phone\n          photoUrl\n          isBlacklisted\n          blacklistReason\n          blacklistedAt\n        }\n        unit {\n          id\n          building {\n            id\n            name\n          }\n        }\n      }\n      pagination {\n        currentPage\n        itemsPerPage\n        totalItems\n        totalPages\n        hasNextPage\n        hasPreviousPage\n      }\n    }\n  }\n"): (typeof documents)["\n  query MisVisitas($pagination: PaginationInput, $filters: FilterVisitsInput) {\n    myVisits(pagination: $pagination, filters: $filters) {\n      items {\n        id\n        type\n        status\n        purpose\n        expectedArrivalAt\n        expectedArrivalUntil\n        qrToken\n        qrUsed\n        qrExpiresAt\n        vehiclePlate\n        entryTime\n        exitTime\n        createdAt\n        visitor {\n          id\n          name\n          lastName\n          identity\n          identityType\n          phone\n          photoUrl\n          isBlacklisted\n          blacklistReason\n          blacklistedAt\n        }\n        unit {\n          id\n          building {\n            id\n            name\n          }\n        }\n      }\n      pagination {\n        currentPage\n        itemsPerPage\n        totalItems\n        totalPages\n        hasNextPage\n        hasPreviousPage\n      }\n    }\n  }\n"];

export function graphql(source: string) {
  return (documents as any)[source] ?? {};
}

export type DocumentType<TDocumentNode extends DocumentNode<any, any>> = TDocumentNode extends DocumentNode<  infer TType,  any>  ? TType  : never;